spring:
  application:
    name: venta-service

  datasource:
    url: jdbc:mysql://localhost:3306/ventaeventos_venta?serverTimezone=UTC
    username: ${USER_BBDD}
    password: ${PASSWORD_BBDD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
