spring:
  application:
    name: evento-service

  datasource:
    url: jdbc:mysql://localhost:3306/ventaeventos_evento?serverTimezone=UTC
    username: maxi
    password: 1660

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
