spring:
  application:
    name: usuario-service
  datasource:
    url: jdbc:mysql://localhost:3306/ventaeventos_usuario?serverTimezone=UTC
    username: ${USER_BBDD}
    password: ${PASSWORD_BBDD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
