spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maxicarabajal/VentaEntradas
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

server:
  port: 8080